# Generated by Django 4.2.7 on 2023-11-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
